### PR TITLE
Added silenceUser() and unsilenceUser()

### PR DESCRIPTION
**Pull request by stevenoh93**
Adding silenceUser(), the user can still post messages to the widget, but the message will not be answered by the bot. This is useful for live agent handoff.

### CODE REVIEW

**Comment by najimovi** [comment]
the behavior to display a message while not sending it to the bot server is already covered in the API by [IBMChat.sendMock()](https://github.com/watson-virtual-agents/chat-widget/blob/master/docs/JSDOCS.md#ibmchatsendmockmessage):

`Send a message to the chat widget from outside the chat widget. This message will be displayed in the interface, but will not actually get sent to the server.`

What would be the benefits of having these and use cases that would not already be covered by our API?

**Comment by stevenoh93** [comment]
`IBMChat.sendMock()` allows the developer to send a message as the user, but if we want the user to construct the message, we have no way of stopping that message from getting to the bot.

The main use case I need is this:

- User triggers an Escalate to Agent intent, and I send a Slack message to a predefined channel. 
- A support agent replies on the Slack channel, and the message is forwarded back to the chat widget. 
- User responds on the chat widget
- Both the agent and the bot respond to the user.
The desired behavior would be that user's message is *not* sent to the bot here. I tried using `IBMChat.sendMock(message)` in the `send` event, but that doesn't stop the bot from responding.

**Comment by ethanwinters** [comment]
So let me try to explain back to I can understand. 

You want to be able to allow people to type into the input field and intercept the message and not allow it to forward on to the bot.

While .sendMock allows you to push text into the view, it doesn't allow you to manage the input field and control the behavior that happens when a user pushes "enter". 

If the above is a correct understanding, I think the discussion worth having is whether silence/unsilence is the correct approach, OR something like the following.

```
IBMChat.handleInput({
    default: false
    callback: function(message) {
          //send to slack bot
     }
});
// and then when you are ready to return control to bot
IBMChat.handleInput({ 
     default: true
});
```

I think the benefit to this latter approach is that it prevents an implementer from having to do any DOM scripting after they have silenced the input and has a chance to be far more stable if we end up making the input field more robust in the future.

Thoughts?

**Comment by ethanwinters** [comment]
I like your approach, but it does seem to require more knowledge of the internal workings of the event system than I would prefer for what could be a fairly common use case. 

Lets go with the handleInput idea, although, if you can think of a better name for that method, I am all ears as I don't love it. We can store whether there is an override callback in state and then handle the if/else in the 'send' event handler.

In addition to `default` and `callback` we should also have an optional `context` key in the passed object that we can call .bind with if it is set.

**Comment by stevenoh93** [comment]
sounds like a plan. Do you think we can get this implemented soon?

**Comment by ethanwinters** [comment]
https://github.com/watson-virtual-agents/chat-widget/pull/25

We will publish an alpha version to npm tomorrow with the changes. I'll put the deployed URL and `npm install` instructions here when it is done.

**Pull request closed without merging**
